#include "WaterTestProtocol.h"
#include <cassert>
#include <iostream>
using namespace WaterTestCore;
using namespace WaterTestProtocol;
int main() {
  const std::string id = "a7380ef0-73be-4bab-9ac8-8f3199a8e025";
  const char *guid = "123456780000ABCD";
  const char *boot = "87dd2780-7b53-49d3-9fa7-a2c4acde0de4";
  const std::string batch = batchIdentifier(id, 12);
  assert(batch == batchIdentifier(id, 12));
  assert(batch != batchIdentifier(id, 24));
  assert(batch.substr(0, 28) == id.substr(0, 28));
  assert(batch.size() == 36);
  Record r{};
  r.kind = 2;
  r.role = 1;
  r.flags = 1 | 2;
  r.raw = -10;
  r.seq = 12;
  r.read_us = 123456789;
  r.t_us = r.read_us + 100;
  r.conversion_us = 750000;
  JsonDocument doc;
  recordToJson(doc.to<JsonObject>(), r, boot, .25);
  assert(doc["sensor_role"] == "glycol");
  assert(doc["raw_c"] == -.625);
  assert(doc["adjusted_c"] == -.375);
  assert(doc["read_us"].as<uint64_t>() == r.read_us);
  assert(doc["conversion_start_us"].as<uint64_t>() == r.read_us - 750000);
  assert(doc["sample_age_us"] == 100);
  assert(doc["pump_on"] == true);
  assert(doc["heater_on"] == false);
  assert(doc["boot_id"] == boot);
  r.flags = 0;
  doc.clear();
  recordToJson(doc.to<JsonObject>(), r, boot, 0);
  assert(doc["quality"] == "sensor_error");
  assert(doc["raw_c"].isNull());
  assert(doc["raw_sixteenths_c"].isNull());
  assert(doc["adjusted_c"].isNull());
  r.kind = 3;
  r.role = 0;
  r.flags = 2 | 4 | 8;
  r.code = static_cast<uint8_t>(Reason::Pilot);
  doc.clear();
  recordToJson(doc.to<JsonObject>(), r, boot, 0);
  assert(doc["type"] == "output");
  assert(doc["applied_on"] == true);
  assert(doc["requested_on"] == true);
  assert(doc["edge"] == true);
  r.role = 1;
  r.flags = 0;
  doc.clear();
  recordToJson(doc.to<JsonObject>(), r, boot, 0);
  assert(doc["applied_on"] == false);
  r.kind = 1;
  r.read_us = 1790380800100000ULL;
  doc.clear();
  recordToJson(doc.to<JsonObject>(), r, boot, 0);
  assert(doc["utc_us"].as<uint64_t>() == r.read_us);
  JsonDocument ack;
  ack["test_id"] = id;
  ack["device_guid"] = guid;
  ack["status"] = "stored";
  ack["batch_id"] = batch;
  auto range = ack["accepted_ranges"].to<JsonArray>().add<JsonArray>();
  range.add(12);
  range.add(23);
  assert(batchAcknowledged(ack, id, guid, batch, 12, 23));
  ack["status"] = "already_present";
  assert(batchAcknowledged(ack, id, guid, batch, 12, 23));
  assert(!batchAcknowledged(ack, id, guid, batch, 12, 24));
  assert(!batchAcknowledged(ack, id, guid, batchIdentifier(id, 24), 12, 23));
  ack["device_guid"] = "WRONG";
  assert(!batchAcknowledged(ack, id, guid, batch, 12, 23));
  ack["device_guid"] = guid;
  ack["accepted_ranges"][0][0] = nullptr;
  assert(!batchAcknowledged(ack, id, guid, batch, 0, 23));
  ack["upload_status"] = "complete";
  ack["finish_received"] = true;
  ack["missing_record_count"] = 0;
  assert(finishAcknowledged(ack, id, guid));
  ack["missing_record_count"] = 1;
  assert(!finishAcknowledged(ack, id, guid));
  ack["missing_record_count"] = nullptr;
  assert(!finishAcknowledged(ack, id, guid));
  ack["missing_record_count"] = 0;
  ack["finish_received"] = false;
  assert(!finishAcknowledged(ack, id, guid));
  ack["finish_received"] = true;
  ack["upload_status"] = "receiving";
  assert(!finishAcknowledged(ack, id, guid));
  ack["upload_status"] = "partial";
  assert(finishAcknowledged(ack, id, guid));
  std::cout
      << "water_test_protocol: raw timing, sensor errors, output edges and durable acknowledgement tests passed\n";
}
